export const LOAD_DAYS_SUCCESS = 'LOAD_DAYS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX CALL ERROR';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const LOAD_LOCATION = 'LOAD_LOCATION';